name: meal_prep_planner

services:
    sql-db:
        container_name: supabase-db
        image: supabase/postgres:15.8.1.085
        volumes:
          - ./Database/00_CreateTables.sql:/docker-entrypoint-initdb.d/init-scripts/98_CreateTables.sql:Z
          - ./Database/01_CreateRoles.sql:/docker-entrypoint-initdb.d/init-scripts/99_CreateRoles.sql:Z
          - DatabaseData:/var/lib/postgresql/data

        ports:
            - "5432:${POSTGRES_PORT:-5432}"
        environment:
            PGPORT: ${POSTGRES_PORT:-5432}
            POSTGRES_PORT: ${POSTGRES_PORT:-5432}
            PGPASSWORD: ${POSTGRES_PASSWORD:-supabase_password}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-supabase_password}
            PGDATABASE: ${POSTGRES_DB:-supabase_db}
            POSTGRES_DB: ${POSTGRES_DB:-supabase_db}
            SCHEMA_DB: ${SCHEMA_DB:-meal_prep}

            DB_ROLE_LOAD_DATA_PASS: ${DB_ROLE_LOAD_DATA_PASS:-load_data_pass}
            DB_ROLE_READ_DATA_PASS: ${DB_ROLE_READ_DATA_PASS:-read_data_pass}

            JWT_SECRET: ${JWT_SECRET}
        
        healthcheck:
            test: ["CMD","pg_isready","-U","postgres","-h","localhost"]
            interval: 5s
            timeout: 5s
            retries: 10
        command: ["postgres","-c","config_file=/etc/postgresql/postgresql.conf",]

    restful-api:
        container_name: supabase-restapi
        image: postgrest/postgrest:v14.8

        ports:
            - "2345:${POSTGREST_PORT:-2345}"
        
        environment:
            PGRST_SERVER_PORT: ${POSTGREST_PORT:-2345}
            PGRST_DB_URI: postgres://authenticator:${POSTGRES_PASSWORD:-supabase_password}@sql-db:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-supabase_db}
            PGRST_DB_SCHEMAS: ${PGRST_DB_SCHEMAS:-${SCHEMA_DB:-meal_prep},public}
            PGRST_DB_EXTRA_SEARCH_PATH: ${PGRST_DB_EXTRA_SEARCH_PATH:-public}

            PGRST_DB_ANON_ROLE: reader_data

            PGRST_JWT_SECRET: ${JWT_JWKS:-${JWT_SECRET}}
            PGRST_APP_SETTINGS_JWT_SECRET: ${JWT_SECRET}
            PGRST_DB_USE_LEGACY_GUCS: "false"

        depends_on:
            sql-db:
                condition: service_healthy
        command: ["postgrest"]

volumes:
    DatabaseData: